server.port: 8000

# Download buffer size in bytes. Default 8192
#jhfs.fs.download.bufferSize: 131072

jhfs.fs.charset: utf8
jhfs.fs.descriptors:

  - id: welcome
    displayName: Welcome
    uri: file:///var/jhfs/welcome
    description: "<p>"
